### PR TITLE
Added shim class to facilitate late binding

### PR DESCRIPTION
**Pull request by joinr**
lein uberjar now works for me:

```bash
Created /home/tom/repos/libpython-clj-uberjar-test/target/libpython-clj-uberjar-test-0.1.0-SNAPSHOT-standalone.jar
tom@that-place:~/repos/libpython-clj-uberjar-test$ java -jar target/libpython-clj-uberjar-test-0.1.0-SNAPSHOT-standalone.jar 
Feb 25, 2020 6:15:50 PM clojure.tools.logging$eval500$fn__503 invoke
INFO: Executing python initialize with options:{:python-executable nil, :program-name nil, :python-home nil, :library-path nil}
Feb 25, 2020 6:15:50 PM clojure.tools.logging$eval500$fn__503 invoke
INFO: Detecting startup-info for Python executable: 
Feb 25, 2020 6:15:50 PM clojure.tools.logging$eval500$fn__503 invoke
INFO: Startup info detected: {:python-home "/usr", :lib-version "3.5", :libname "python3.5m", :java-library-path-addendum "/usr/lib"}
Feb 25, 2020 6:15:50 PM clojure.tools.logging$eval500$fn__503 invoke
INFO: Reference thread starting
Feb 25, 2020 6:15:50 PM clojure.tools.logging$eval500$fn__503 invoke
INFO: Library python3.5m found at [:system "python3.5m"]
Feb 25, 2020 6:15:51 PM clojure.tools.logging$eval500$fn__503 invoke
INFO: Library c found at [:system "c"]
Hi
[0.         0.04081633 0.08163265 0.12244898 0.16326531 0.20408163
 0.24489796 0.28571429 0.32653061 0.36734694 0.40816327 0.44897959
 0.48979592 0.53061224 0.57142857 0.6122449  0.65306122 0.69387755
 0.73469388 0.7755102  0.81632653 0.85714286 0.89795918 0.93877551
 0.97959184 1.02040816 1.06122449 1.10204082 1.14285714 1.18367347
 1.2244898  1.26530612 1.30612245 1.34693878 1.3877551  1.42857143
 1.46938776 1.51020408 1.55102041 1.59183673 1.63265306 1.67346939
 1.71428571 1.75510204 1.79591837 1.83673469 1.87755102 1.91836735
 1.95918367 2.        ]

```

### CODE REVIEW

**Comment by cnuernber** [comment]
That is interesting for sure.  But it won't solve the graalvm-native pathway I do not believe.

I think for graalvm-native you will have to use just the base libpython-clj.python namespace among other things.

**Comment by joinr** [comment]
This just gets you around uber jars and the entry point not finding the required classes (since python stuff isn't AOT'd).  native-image is a whole other can of worms.

**Comment by joinr** [comment]
Yeah, trying to use stuff from the python ns (as in some of the examples in the libpython-clj test code) is not going well with graal either.  I keep tripping the classloader somewhere.

**Comment by gigasquid** [comment]
This is great - thanks @joinr 😄 

I don't know if it's even possible with libpython-clj to even do graal native image with this limitation
https://blog.taylorwood.io/2018/05/02/graalvm-clojure.html

```To achieve such aggressive ahead-of-time optimizations, we run an aggressive static analysis that requires a closed-world assumption. We need to know all classes and all bytecodes that are reachable at run time. Therefore, it is not possible to load new classes that have not been available during ahead-of-time-compilation.```

**Pull request merged**
